---
name: Deploy

on:
  workflow_call:

permissions: { }

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      # Set up access to push to repo. LFS is not required because only the artifact will be used.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Configure git
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      # The new branch contains only the files from the artifact.
      - name: Commit and force push
        run: |
          git switch -c cf-pages/${{ github.ref_name }}
          git rm -rf .
          mv artifact/* .
          rmdir artifact

          git add -A -f
          git commit -m "chore: ${{ github.workflow }} ${GITHUB_SHA:0:7}"
          git push -f origin cf-pages/${{ github.ref_name }}
