name: Export and deploy
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - cloudflare_headers
      - src/**
    types:
      - closed
  push:
    branches:
      - dev
    paths:
      - .github/**
      - cloudflare_headers
      - src/**
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  PROJECT_PATH: src

jobs:
  export:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup container
        run: |
          apt update
          apt install -y brotli
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Build
        run: |
          mkdir -v -p build
          cd ${{ env.PROJECT_PATH }}
          godot --headless --verbose --export-release Web ../build/index.html
          cp ../cloudflare_headers ../build/_headers

      - name: Hash wasm
        id: hash-wasm
        run: echo "sha=${{ hashFiles('build/index.wasm') }}" > "$GITHUB_OUTPUT"

      # The exported wasm file may differ based on what is included in your project.
      # If there are significant changes, using the cache may be inappropriate.
      - name: Cache compressed Godot WebAssembly
        id: cache-wasm
        uses: actions/cache@v4
        with:
          path: build/index.wasm
          key: ${{ steps.hash-wasm.outputs.sha }}

      - name: Brotli compression
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        run: |
          cd build
          brotli index.wasm
          ls -hl
          mv index.wasm.br index.wasm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          if-no-files-found: error
          retention-days: 1

  # Deploy is a separate job because it requires elevated permissions.
  deploy:
    runs-on: ubuntu-22.04
    needs: export
    permissions:
      contents: write

    steps:
      # Set up access to push to repo. LFS is not required because only the artifact will be used.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Configure git
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      # The new branch contains only the files from the artifact.
      - name: Commit and force push
        run: |
          git switch -c cf-pages/${{ github.ref_name }}
          git rm -rf .
          mv artifact/* .
          rmdir artifact

          git add --all
          git commit -m "chore: ${{ github.workflow }} ${GITHUB_SHA:0:7}"
          git push -f origin cf-pages/${{ github.ref_name }}
