---
name: GDScript Toolkit

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.gd'

  workflow_dispatch:

permissions: { }

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GDScript Toolkit
        uses: Scony/godot-gdscript-toolkit@4.2.2

      - name: gdformat
        run: gdformat --check src/

      - name: gdlint
        run: gdlint src/
