name: Manual Export
on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  PROJECT_PATH: godot-cf-pages

jobs:
  export:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build
          cd $PROJECT_PATH
          godot --headless --verbose --export-release Web ../build/index.html
