name: Manual Export
on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  PROJECT_PATH: godot-cf-pages

jobs:
  export:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          apt update
          apt install -y brotli
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: |
          mkdir -v -p build
          cd ${PROJECT_PATH}
          godot --headless --verbose --export-release Web ../build/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          if-no-files-found: error
          retention-days: 1

  deploy:
    runs-on: ubuntu-22.04
    needs: export
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Commit and push
        run: |
          ls -l
          ls -l artifact
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config --global user.name github-actions[bot]
          git config --global user.email ${GITHUB_REPOSITORY_OWNER_ID}+github-actions[bot]@users.noreply.github.com
          git add -f build
          git commit -m "GitHub Actions build: ${GITHUB_SHA}"
          git subtree push --prefix build origin cf-pages
