name: Manual Export
on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  PROJECT_PATH: godot-cf-pages
  BRANCH_NAME: cf-pages

jobs:
  export:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          apt update
          apt install -y brotli
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Build
        run: |
          mkdir -v -p build
          cd ${{ env.PROJECT_PATH }}
          godot --headless --verbose --export-release Web ../build/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          if-no-files-found: error
          retention-days: 1

  deploy:
    runs-on: ubuntu-22.04
    needs: export
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Commit and push
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global user.name github-actions[bot]
          git config --global user.email ${{ github.repository_owner_id }}+github-actions[bot]@users.noreply.github.com

          git switch -c ${{ env.BRANCH_NAME }}
          git rm -rf .
          mv artifact/* .
          rmdir artifact

          git add --all
          git commit -m "chore: ${{ github.workflow }} ${{ github.sha }}"
          git push -f origin ${{ env.BRANCH_NAME }}
